title: Cameron Molina - Portfolio
profile_img: /assets/img/newprofile.webp
icon_img: /assets/img/icon.webp

name: "Cameron Molina"
job: "Seeking Summer 2026 Co-op"
location: "Brecksville, Ohio, United States"

phone_number: 440-666-6847
email: cbmolina13@gmail.com
linkedin_username: Cameron Molina
github_username: CameronBMolina

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: /portfolio/

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
