title: Cameron Molina - Portfolio
profile_img: /assets/img/newprofile.webp
icon_img: /assets/img/icon.webp

name: "Cameron Molina"
job: "Seeking Summer 2026 Co-op"
location: "Brecksville, Ohio, United States"
about: "My name is Cameron Molina and I am a second year undergraduate at the University of Cincinnati. After starting in Civil Engineering and completing my first Co-op at GPD Group in Akron, Ohio, I decided to switch majors. Having been a part of competitive robotics for 6+ years and missing the satisfaction that it gave me I decided to switch to Mechanical Engineering. I recently started the University of Cincinnati Vex U Robotics Club and hope to help it grow into a competitive collegiate team while also building lasting relationships with its members. Contact information and links to my LinkedIn, Github, and resume can be found at the bottom of this page."



# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl: /portfolio/

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
